version: "3.8"

services:
  fastapi:
    env_file:
      - .env
    build: ./fastapi
    ports:
      - "127.0.0.1:8000:8000"
    container_name: fastapi
    volumes:
      - ./fastapi/blacklisted_proxies:/fastapi/blacklisted_proxies 
    depends_on:
      - redis
      - searxng

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  searxng:
    image: searxng/searxng
    ports:
      - '${SEARXNG_PORT:-8080}:8080'
    env_file: .searxng.env
    volumes:
      - ./searxng-limiter.toml:/etc/searxng/limiter.toml
      - ./searxng-settings.yml:/etc/searxng/settings.yml
      - searxng_data:/data

volumes:
  redis_data:
  searxng_data: